import {
  siAngular,
  siBetterauth,
  siClaudecode,
  siClerk,
  siConvex,
  siCplusplus,
  siCursor,
  siDotnet,
  siDrizzle,
  siExpress,
  siGit,
  siGithub,
  siHono,
  siJavascript,
  siNextdotjs,
  siNodedotjs,
  siPostman,
  siPostgresql,
  siPrisma,
  siPython,
  siRider,
  siTypescript,
} from "simple-icons";

export const techIconPaths: Record<string, string> = {
  ".NET": siDotnet.path,
  TypeScript: siTypescript.path,
  JavaScript: siJavascript.path,
  Python: siPython.path,
  "C++": siCplusplus.path,
  "Node.js": siNodedotjs.path,
  Express: siExpress.path,
  Hono: siHono.path,
  Clerk: siClerk.path,
  "Better Auth": siBetterauth.path,
  Angular: siAngular.path,
  "Next.js": siNextdotjs.path,
  PostgreSQL: siPostgresql.path,
  Prisma: siPrisma.path,
  DrizzleORM: siDrizzle.path,
  Convex: siConvex.path,
  Git: siGit.path,
  GitHub: siGithub.path,
  Postman: siPostman.path,
  Rider: siRider.path,
  Cursor: siCursor.path,
  "Claude Code": siClaudecode.path,
};
